# Generated by Django 3.2 on 2021-05-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='রক্তের নাম', max_length=50, null=True, verbose_name='Blood group name')),
                ('code', models.CharField(blank=True, help_text='রক্তের কোড', max_length=50, null=True, verbose_name='Blood group code')),
                ('group', models.CharField(blank=True, help_text='রক্তের গ্রুপ', max_length=50, null=True, verbose_name='Blood group name')),
            ],
        ),
    ]
