# Generated by Django 3.2 on 2021-05-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210504_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='সিস্টেম এর নাম', max_length=50, null=True, verbose_name='System Name')),
                ('logo', models.FileField(blank=True, help_text='সিস্টেম এর প্রতিক', null=True, upload_to='media/logo/', verbose_name='System logo')),
                ('slogan', models.CharField(blank=True, help_text='সিস্টেম এর স্লগান', max_length=100, null=True, verbose_name='Slogan for system')),
            ],
        ),
    ]
