# Generated by Django 3.2 on 2021-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210705_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='profile',
            name='thana',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thana'),
        ),
    ]
