# Generated by Django 3.2 on 2021-07-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210707_0111'),
        ('accounts', '0008_auto_20210707_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.blood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_donate',
            field=models.DateField(blank=True, null=True, verbose_name='Last Donate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_donate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Blood Donate'),
        ),
    ]
