# Generated by Django 3.2 on 2021-07-13 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210707_0111'),
        ('accounts', '0009_auto_20210712_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.blood'),
        ),
    ]
