# Generated by Django 3.2 on 2021-07-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('accounts', '0010_alter_profile_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.upazila'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.district'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.division'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_donate',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Total Blood Donate'),
        ),
    ]
