# Generated by Django 3.2 on 2021-07-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210714_2332'),
        ('accounts', '0011_auto_20210715_0043'),
    ]

    operations = [
    ]
